In [1]:
import torch

a = torch.Tensor(3,3)
print a


 0.0000e+00  0.0000e+00 -6.1804e+16
 4.5736e-41 -1.5903e+10  4.5736e-41
 2.7288e-38  0.0000e+00  6.7262e-44
[torch.FloatTensor of size 3x3]



In [2]:
print a.size()

torch.Size([3, 3])


In [4]:
b = a.numpy()
print b
print torch.from_numpy(b)

[[  0.00000000e+00   0.00000000e+00  -6.18040296e+16]
 [  4.57355793e-41  -1.59034573e+10   4.57355793e-41]
 [  2.72875859e-38   0.00000000e+00   6.72623263e-44]]

 0.0000e+00  0.0000e+00 -6.1804e+16
 4.5736e-41 -1.5903e+10  4.5736e-41
 2.7288e-38  0.0000e+00  6.7262e-44
[torch.FloatTensor of size 3x3]



In [5]:
# -*- coding: utf-8 -*-
import numpy as np
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

# requires_grad 表示是否对其求梯度，默认是True
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2*x + y + 4

# 对x和y分别求导
print z.backward()

# x的导数和y的导数
print('dz/dx:{}'.format(x.grad.data))
print('dz/dy:{}'.format(y.grad.data))

None
dz/dx:
 2
[torch.FloatTensor of size 1]

dz/dy:
 1
[torch.FloatTensor of size 1]



In [6]:
# -*- coding: utf-8 -*-
import numpy as np
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

# 基本的网络构建类模版
class net_name(nn.Module):
    def __init__(self):
        super(net_name,self).__init__()
        # 可以添加子网络
        self.conv1 = nn.Conv2d(3,10,3)
        # 具体每种层的参数可以查看文档

    def forward(self, x):
        # 定向前传播
        out = self.conv1(x)
        return out